import React, { useState, Fragment } from 'react';
import { X, ChevronDown, Clipboard, AlertCircle, ChevronLeft, Info, Eye } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Patient } from '../services/api';
import { GeminiContentResponse } from '../types';
import { useTheme } from '../theme';
import VisionSlider from './VisionSlider';
import CataractTypeCard from './CataractTypeCard';
import {
    getCataractTypeFromId,
    getOtherCataractTypes,
    getCataractVisionEffect,
    CataractType,
} from '../data/cataractTypes';

interface DiagnosisModalProps {
    patient: Patient | null;
    moduleContent: GeminiContentResponse | null;
    onClose: () => void;
    onOpenChat: (initialMessage?: string) => void;
}

type TabType = 'visual' | 'anatomical';

const DiagnosisModal: React.FC<DiagnosisModalProps> = ({
    patient,
    moduleContent,
    onClose,
    onOpenChat,
}) => {
    const [activeTab, setActiveTab] = useState<TabType>('visual');
    const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(null);
    const [selectedOtherCataract, setSelectedOtherCataract] = useState<CataractType | null>(null);
    const { classes } = useTheme();

    // Extract patient diagnosis data
    const diagnosis = patient?.clinical_context?.diagnosis;
    const diagnosisType = diagnosis?.type || 'Cataract';
    const pathology = diagnosis?.pathology || '';
    const primaryCataractType = diagnosis?.primary_cataract_type; // NEW: structured field
    const comorbidities = patient?.clinical_context?.comorbidities || [];
    const symptoms = patient?.clinical_context?.symptoms_reported_by_patient || [];
    const examDate = patient?.surgical_recommendations_by_doctor?.decision_date || '';

    // Use structured field for cataract type lookup
    const patientCataractType = getCataractTypeFromId(primaryCataractType);
    const otherCataractTypes = getOtherCataractTypes(primaryCataractType);
    const visionEffect = getCataractVisionEffect(primaryCataractType);

    // Get the primary cataract image from structured field
    const primaryCataractImage = patientCataractType?.eyeImage || '/assets/diagnosis/eye_nuclear_sclerosis.png';

    // Pathology tags (e.g., "Nuclear Sclerosis (1-2+)", "Cortical (2+)")
    const pathologyTags = pathology.split(' and ').map(t => t.trim()).filter(Boolean);

    // Patient name - use the correct Patient interface fields
    const patientName = patient?.name
        ? `${patient.name.first} ${patient.name.last?.charAt(0) || ''}.`
        : 'Patient';


    // Format exam date
    const formattedExamDate = examDate
        ? new Date(examDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
        : '';

    // Use summary from module content (generated by AI)
    const descriptionText = moduleContent?.summary || '';

    const sanitizeQuestion = (q?: string) =>
        (q || '')
            .replace(/\*\*/g, '')
            .replace(/__/g, '')
            .replace(/`+/g, '')
            .replace(/\s+/g, ' ')
            .trim();

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 animate-[fadeIn_0.2s_ease-out]">
            {/* Backdrop */}
            <div
                className="absolute inset-0 bg-black/40 backdrop-blur-sm"
                onClick={onClose}
            />

            {/* Modal Container */}
            <div className="relative w-full max-w-7xl max-h-[96vh] bg-white rounded-3xl shadow-2xl overflow-hidden flex flex-col animate-[scaleIn_0.2s_ease-out]">
                {/* Close Button */}
                <button
                    onClick={onClose}
                    className="absolute top-5 right-5 z-10 p-2 bg-slate-100 hover:bg-slate-200 rounded-full transition-colors text-slate-600"
                >
                    <X size={22} />
                </button>

                {/* Scrollable Content */}
                <div className="overflow-y-auto" style={{ scrollbarGutter: 'stable' }}>
                    {/* Header */}
                    <div className="px-8 pt-8 pb-4">
                        <h1 className="text-3xl font-bold text-slate-900 mb-1">My Diagnosis</h1>
                        <p className="text-sm text-slate-500">
                            Patient: <span className="text-slate-700 font-medium">{patientName}</span>
                            {formattedExamDate && (
                                <> • Exam Date: <span className="text-slate-700">{formattedExamDate}</span></>
                            )}
                        </p>
                    </div>

                    {/* Main Content - Two Column Layout */}
                    <div className="px-8 pb-6">
                        <div className="flex flex-col lg:flex-row gap-6">
                            {/* Left Column - Diagnosis Info */}
                            <div className={`flex-1 ${classes.surfaceVariant} rounded-2xl p-6 border ${classes.cube.rightBorder}`}>
                                {/* Primary Diagnosis Header */}
                                <div className="flex items-start justify-between mb-4">
                                    <div className="flex items-center gap-2">
                                        <Clipboard size={18} className={classes.primaryText} />
                                        <span className={`text-sm font-semibold ${classes.primaryText} uppercase tracking-wide`}>
                                            Primary Diagnosis
                                        </span>
                                    </div>
                                    <span className="px-3 py-1 bg-emerald-100 text-emerald-700 text-xs font-bold uppercase tracking-wide rounded-full">
                                        Confirmed
                                    </span>
                                </div>

                                {/* Diagnosis Title */}
                                <h2 className={`text-2xl font-bold ${classes.cube.rightTitle} mb-3`}>
                                    {diagnosisType}
                                </h2>

                                {/* Pathology Tags */}
                                <div className="flex flex-wrap gap-2 mb-4">
                                    {pathologyTags.map((tag, i) => (
                                        <span
                                            key={i}
                                            className={`px-3 py-1.5 bg-white border ${classes.cube.rightBorder} rounded-lg text-sm font-medium ${classes.primaryText}`}
                                        >
                                            {tag}
                                        </span>
                                    ))}
                                </div>

                                {/* Description from Module Content */}
                                <div className="text-slate-600 leading-relaxed mb-5 text-sm [&>p]:mb-3 last:[&>p]:mb-0">
                                    <ReactMarkdown>{descriptionText}</ReactMarkdown>
                                </div>

                                {/* Additional Conditions (conditional rendering) */}
                                {comorbidities.length > 0 && (
                                    <div className="bg-white rounded-xl p-4 border border-slate-200">
                                        <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wide mb-2">
                                            Additional Conditions
                                        </h4>
                                        <ul className="space-y-1">
                                            {comorbidities.map((condition, i) => (
                                                <li key={i} className="flex items-center gap-2 text-sm text-slate-700">
                                                    <span className="w-1.5 h-1.5 rounded-full bg-amber-400" />
                                                    {condition}
                                                </li>
                                            ))}
                                        </ul>
                                    </div>
                                )}
                            </div>

                            {/* Right Column - Visual Tabs */}
                            <div className="lg:w-[380px] flex flex-col">
                                {/* Tab Headers */}
                                <div className="flex border-b border-slate-200 mb-4">
                                    <button
                                        onClick={() => setActiveTab('visual')}
                                        className={`flex-1 py-3 text-sm font-semibold transition-colors relative ${activeTab === 'visual'
                                            ? 'text-violet-600'
                                            : 'text-slate-500 hover:text-slate-700'
                                            }`}
                                    >
                                        Visual Simulation
                                        {activeTab === 'visual' && (
                                            <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-violet-600" />
                                        )}
                                    </button>
                                    <button
                                        onClick={() => setActiveTab('anatomical')}
                                        className={`flex-1 py-3 text-sm font-semibold transition-colors relative ${activeTab === 'anatomical'
                                            ? 'text-violet-600'
                                            : 'text-slate-500 hover:text-slate-700'
                                            }`}
                                    >
                                        Anatomical View
                                        {activeTab === 'anatomical' && (
                                            <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-violet-600" />
                                        )}
                                    </button>
                                </div>

                                {/* Tab Content */}
                                <div className="flex-1 h-[280px] rounded-2xl overflow-hidden bg-slate-100">
                                    {activeTab === 'visual' ? (
                                        <VisionSlider
                                            leftImage="/assets/diagnosis/landscape_scene.jpg"
                                            rightImage="/assets/diagnosis/landscape_scene.jpg"
                                            leftLabel="Healthy Vision"
                                            rightLabel="Your Vision"
                                            rightFilter={visionEffect}
                                            caption={`Effect of ${patientCataractType?.name || 'Cataract'} on clarity`}
                                        />
                                    ) : (
                                        <VisionSlider
                                            leftImage="/assets/diagnosis/eye_healthy.png"
                                            rightImage={primaryCataractImage}
                                            leftLabel="Healthy Eye"
                                            rightLabel="Your Eye"
                                            caption={`${diagnosisType} - Anatomical comparison`}
                                        />
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Other Cataract Types Section */}
                    {otherCataractTypes.length > 0 && (
                        <div className="px-8 pb-6">
                            <h3 className={`text-lg font-bold mb-4 flex items-center gap-2 ${classes.primaryText}`}>
                                <Info size={20} />
                                Other Cataract Types
                            </h3>

                            {/* Animated Container */}
                            <div className="relative min-h-[300px]">
                                {/* List View */}
                                {!selectedOtherCataract ? (
                                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 animate-fadeIn">
                                        {otherCataractTypes.map((cataract) => (
                                            <CataractTypeCard
                                                key={cataract.id}
                                                cataract={cataract}
                                                onClick={() => setSelectedOtherCataract(cataract)}
                                                className="h-full"
                                            />
                                        ))}
                                    </div>
                                ) : (
                                    /* Detail View Overlay */
                                    <div className="animate-slideIn relative bg-slate-50 rounded-2xl border border-slate-200 overflow-hidden shadow-sm">
                                        {/* Header */}
                                        <div className="bg-white border-b border-slate-200 p-4 flex items-center gap-3 sticky top-0 z-10">
                                            <button
                                                onClick={() => setSelectedOtherCataract(null)}
                                                className="p-2 hover:bg-slate-100 rounded-full transition-colors text-slate-500 hover:text-slate-800"
                                            >
                                                <ChevronLeft size={24} />
                                            </button>
                                            <div>
                                                <h3 className="text-xl font-bold text-slate-800">{selectedOtherCataract.name}</h3>
                                                <p className="text-sm text-slate-500">Detailed View & Vision Simulation</p>
                                            </div>
                                        </div>

                                        <div className="p-6 overflow-y-auto max-h-[600px]">
                                            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                                                {/* Left: Description & Symptoms */}
                                                <div className="space-y-6">
                                                    <div className="bg-white p-5 rounded-xl border border-slate-100 shadow-sm">
                                                        <h4 className="flex items-center gap-2 text-sm font-semibold text-slate-700 mb-3 uppercase tracking-wide">
                                                            <Info size={16} className="text-blue-500" />
                                                            Condition Overview
                                                        </h4>
                                                        <p className="text-slate-600 leading-relaxed whitespace-pre-line">
                                                            {selectedOtherCataract.detailedDescription}
                                                        </p>
                                                    </div>

                                                    <div>
                                                        <h4 className="flex items-center gap-2 text-sm font-semibold text-slate-700 mb-3 uppercase tracking-wide">
                                                            <AlertCircle size={16} className="text-amber-500" />
                                                            Common Symptoms
                                                        </h4>
                                                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                                                            {selectedOtherCataract.symptoms.map((symptom, idx) => (
                                                                <div key={idx} className="flex items-center gap-3 bg-white p-3 rounded-lg border border-slate-100 shadow-sm">
                                                                    <div className={`w-2 h-2 rounded-full ${selectedOtherCataract.color.replace('bg-', 'bg-').replace('-100', '-500')}`} />
                                                                    <span className="text-sm font-medium text-slate-700">{symptom}</span>
                                                                </div>
                                                            ))}
                                                        </div>
                                                    </div>
                                                </div>

                                                {/* Right: Anatomical View */}
                                                <div>
                                                    <h4 className="flex items-center gap-2 text-sm font-semibold text-slate-700 mb-3 uppercase tracking-wide">
                                                        <Eye size={16} className="text-purple-500" />
                                                        Anatomical View
                                                    </h4>
                                                    <div className="bg-slate-900 rounded-xl overflow-hidden shadow-lg border border-slate-700 h-[300px] relative">
                                                        <VisionSlider
                                                            leftImage="/assets/diagnosis/eye_healthy.png"
                                                            rightImage={selectedOtherCataract.eyeImage}
                                                            leftLabel="Healthy Eye"
                                                            rightLabel={selectedOtherCataract.shortName}
                                                            caption={`Anatomical appearance of ${selectedOtherCataract.name}`}
                                                        />
                                                    </div>
                                                    <p className="text-xs text-slate-500 mt-2 text-center italic">
                                                        * Representation of how the lens looks with this condition.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}        {/* FAQs Section */}
                    {moduleContent?.faqs && moduleContent.faqs.length > 0 && (
                        <div className="px-8 pb-6">
                            <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">
                                Frequently Asked Questions
                            </h3>
                            <div className="space-y-3">
                                {moduleContent.faqs.map((faq, index) => {
                                    const isOpen = openFaqIndex === index;
                                    return (
                                        <div
                                            key={index}
                                            className={`rounded-2xl border transition-all duration-300 overflow-hidden ${isOpen
                                                ? 'bg-violet-50/50 border-violet-200 shadow-sm'
                                                : 'bg-white border-slate-200 hover:border-slate-300'
                                                }`}
                                        >
                                            <button
                                                onClick={() => setOpenFaqIndex(isOpen ? null : index)}
                                                className="w-full text-left p-5 flex justify-between items-start gap-4"
                                            >
                                                <div
                                                    className={`font-medium text-base transition-colors ${isOpen ? 'text-violet-800' : 'text-slate-700'
                                                        }`}
                                                >
                                                    <ReactMarkdown components={{ p: Fragment }}>{faq.question}</ReactMarkdown>
                                                </div>
                                                <span
                                                    className={`flex-shrink-0 p-1.5 rounded-full transition-all duration-300 ${isOpen
                                                        ? 'rotate-180 bg-violet-200 text-violet-700'
                                                        : 'bg-slate-100 text-slate-400'
                                                        }`}
                                                >
                                                    <ChevronDown size={18} />
                                                </span>
                                            </button>

                                            <div
                                                className={`transition-all duration-300 ease-in-out overflow-hidden ${isOpen ? 'max-h-[500px] opacity-100' : 'max-h-0 opacity-0'
                                                    }`}
                                            >
                                                <div className="p-5 pt-0 text-slate-600 leading-relaxed text-sm">
                                                    <div className="h-px w-full bg-slate-200/60 mb-4" />
                                                    <ReactMarkdown>{faq.answer || ''}</ReactMarkdown>
                                                </div>
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        </div>
                    )}

                    {/* Chat CTA Footer */}
                    <div className="px-8 pb-8">
                        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-5 bg-slate-50 rounded-2xl border border-slate-200">
                            <div>
                                <h4 className="text-violet-600 font-semibold mb-1">Still have questions?</h4>
                                <p className="text-sm text-slate-600">
                                    Our AI assistant can explain your charts based on your records.
                                </p>
                            </div>
                            <button
                                onClick={() =>
                                    onOpenChat(
                                        sanitizeQuestion(moduleContent?.botStarterPrompt) ||
                                        `Tell me more about my ${diagnosisType} diagnosis`
                                    )
                                }
                                className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-violet-600 text-white font-medium shadow-lg hover:bg-violet-700 hover:shadow-xl hover:scale-105 transition-all whitespace-nowrap"
                            >
                                <svg
                                    width="18"
                                    height="18"
                                    viewBox="0 0 24 24"
                                    fill="none"
                                    stroke="currentColor"
                                    strokeWidth="2"
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                >
                                    <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
                                </svg>
                                Chat with Assistant
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default DiagnosisModal;
